version: '3'

services:
    nginx:
        build: ./nginx
        ports:
        - "80:80"
    db:
        image: postgres
        restart: always
        volumes:
            - ./docker/data:/var/lib/postgres/data
        env_file:
            - .env.db.docker
        ports:
            - '5432:5432'
    api:
        build:
            context: .
            dockerfile: ./Dockerfile
        restart: always
        volumes:
            - ./logs:/anam-food-backend/logs
        command:
            - bash
            - -c
            - |
                ./wait-for-it.sh db:5432 -t 10
                yarn prod
