name: Run on dev server
on:
    push:
        branches:
            - master

jobs:
    test-code:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: appleboy/ssh-action@master
              with:
                  host: ${{ secrets.HOST }}
                  username: ${{ secrets.USERNAME }}
                  key: ${{ secrets.KEY }}
                  script: |
                      cd ~/anam-food-backend
                      git pull
                      docker-compose up -d --build
