name: Test code
on:
    push:
        branches:
            - master
    pull_request:
        branches:
            - master

jobs:
    test-code:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: borales/actions-yarn@v2.0.0
              with:
                cmd: test