name: Test code
on:
    push:
        branches:
            - master
    pull_request:
        branches:
            - master

jobs:
    test-code:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v1
              with:
                  node-version: '12'
              env:
                  ORM_HOST: ${{secrets.ORM_HOST}}
                  ORM_PORT: ${{secrets.ORM_PORT}}
                  ORM_USERNAME: ${{secrets.ORM_USERNAME}}
                  ORM_PASSWORD: ${{secrets.ORM_PASSWORD}}
                  ORM_DATABASE: ${{secrets.ORM_DATABASE}}
            - run: yarn
            - run: yarn test
            - run: yarn build
